import { NextRequest, NextResponse } from 'next/server';
import { getTokenFromRequest, verifyToken } from '@/lib/auth';
import { query } from '@/lib/db';

export async function POST(req: NextRequest) {
  try {
    const token = getTokenFromRequest(req);
    if (!token) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const decoded = verifyToken(token);
    if (!decoded) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json();
    const { type, opportunityId } = body; // type: 'resume' | 'cover_letter'

    if (!type || !opportunityId) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // 1. Fetch User Profile
    const userRes = await query(
      'SELECT full_name, skills, education, experience FROM users WHERE id = $1',
      [decoded.id]
    );
    const user = userRes.rows[0];

    if (!user || (!user.skills && !user.experience)) {
      return NextResponse.json({ 
        error: 'Profile incomplete', 
        message: 'Please complete your profile (skills and experience) to use the AI Assistant.' 
      }, { status: 400 });
    }

    // 2. Fetch Opportunity Details
    const oppRes = await query(
      'SELECT title, organization, description, category FROM opportunities WHERE id = $1',
      [opportunityId]
    );
    const opp = oppRes.rows[0];

    if (!opp) {
      return NextResponse.json({ error: 'Opportunity not found' }, { status: 404 });
    }

    // 3. AI Generation Logic (MOCKED for now - will provide high-quality template)
    // In production, you would call OpenAI/Gemini here.
    
    let generatedContent = '';
    
    if (type === 'resume') {
      generatedContent = `
# RESUME: ${user.full_name}
Optimized for: ${opp.title} at ${opp.organization}

## PROFESSIONAL SUMMARY
Highly skilled professional with expertise in ${user.skills?.join(', ') || 'relevant fields'}. 
Seeking to leverage my background to contribute to the ${opp.category} team at ${opp.organization}.

## SKILLS
${user.skills?.map((s: string) => `- ${s}`).join('\n') || '- Professional skills'}

## EXPERIENCE
${user.experience || 'Professional experience details...'}

## EDUCATION
${user.education || 'Academic background details...'}

---
*Generated by OppAlert AI Assistant*
      `.trim();
    } else {
      generatedContent = `
Dear Hiring Manager at ${opp.organization},

I am writing to express my strong interest in the ${opp.title} opportunity. 
With my background in ${user.experience?.substring(0, 50)}... and my skills in ${user.skills?.slice(0, 3).join(', ')}, 
I am confident that I would be a valuable asset to your team.

My experience aligns well with the requirements for the ${opp.category} role, particularly my ability to...

Thank you for your time and consideration.

Best regards,
${user.full_name}

---
*Generated by OppAlert AI Assistant*
      `.trim();
    }

    // Simulate AI latency
    await new Promise(resolve => setTimeout(resolve, 1500));

    return NextResponse.json({ 
      success: true, 
      content: generatedContent,
      type
    });

  } catch (error) {
    console.error('AI Career API error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
