import type { Opportunity } from './types'

export const opportunities: Opportunity[] = [
  {
    id: '1',
    icon: '🎓',
    title: 'Chevening Scholarships 2025/26',
    org: 'UK Government · Chevening',
    cat: 'scholarship',
    loc: 'United Kingdom',
    fund: 'Fully Funded',
    deadline: 'Apr 5, 2025',
    days: 20,
    desc: 'Prestigious UK government scholarship for outstanding African professionals to pursue a one-year master\'s degree at any UK university.',
    featured: true,
    about: 'The Chevening Scholarship Programme is the UK government\'s global scholarship programme, offering awards to outstanding individuals with leadership potential. Applications are open to citizens of eligible Chevening countries across Africa. You will study at any UK university of your choice.',
    elig: [
      'Citizen of a Chevening-eligible country',
      'At least 2 years of work experience',
      'Meet the English language requirements',
      'Hold an undergraduate degree equivalent to a UK 2:1',
      'Return to your home country for at least 2 years after studies',
    ],
    benefits: [
      'Full tuition fees at any UK university',
      'Monthly living allowance',
      'Economy class return airfare',
      'Arrival and departure allowance',
      'Travel grant to attend Chevening events in the UK',
    ],
    applyUrl: 'https://www.chevening.org/scholarships/',
    quickinfo: {
      Type: 'Scholarship',
      Duration: '1 year',
      Location: 'United Kingdom',
      Level: 'Postgraduate (Masters)',
      Deadline: 'Apr 5, 2025',
      Funding: 'Fully Funded',
    },
  },
  {
    id: '2',
    icon: '💼',
    title: 'Remote Software Engineer – Fintech',
    org: 'Paystack · Lagos',
    cat: 'job',
    loc: 'Remote (Africa)',
    fund: 'Paid Position',
    deadline: 'Mar 20, 2025',
    days: 5,
    desc: 'Join Nigeria\'s leading payment company as a backend engineer. Fully remote position with competitive USD salary for engineers across Africa.',
    featured: true,
    about: 'Paystack is looking for a talented backend engineer to join our growing platform team. You\'ll work on scalable payment infrastructure that powers thousands of African businesses, processing millions of transactions daily.',
    elig: [
      '3+ years backend engineering experience',
      'Proficiency in Node.js or Python',
      'Experience with PostgreSQL, Redis, and cloud infrastructure',
      'Strong written English communication',
      'Available to work WAT / GMT+1 core hours',
    ],
    benefits: [
      'Competitive USD salary ($60,000–$90,000/year)',
      '100% remote — work from anywhere in Africa',
      'Comprehensive health insurance',
      'Annual equipment stipend ($2,000)',
      'Team offsites and company retreats',
    ],
    applyUrl: 'https://paystack.com/careers',
    quickinfo: {
      Type: 'Full-time Job',
      Duration: 'Permanent',
      Location: 'Remote (Nigeria preferred)',
      Level: 'Mid-Senior',
      Deadline: 'Mar 20, 2025',
      Salary: '$60K–$90K/year',
    },
  },
  {
    id: '3',
    icon: '🌍',
    title: 'Mandela Washington Fellowship 2025',
    org: 'U.S. Department of State',
    cat: 'fellowship',
    loc: 'United States',
    fund: 'Fully Funded',
    deadline: 'May 15, 2025',
    days: 60,
    desc: 'The flagship exchange program for young African leaders, offering 6 weeks of professional development in business, civic leadership, and public management in the USA.',
    featured: false,
    about: 'The Mandela Washington Fellowship for Young African Leaders connects young African leaders with U.S. host institutes, organizations, and universities for 6-week academic institutes focused on leadership, entrepreneurship, and civic engagement.',
    elig: [
      'Ages 25–35 at time of application',
      'Citizen and resident of a sub-Saharan African country',
      'Demonstrated leadership record in community or organization',
      'Not a U.S. citizen or permanent resident',
      'College or university degree not required',
    ],
    benefits: [
      'All-expenses-paid trip to the United States',
      '$50/day living stipend',
      'Housing provided by host institution',
      'Networking with global leaders and alumni',
      'Invitation to Presidential Summit in Washington D.C.',
    ],
    applyUrl: 'https://yali.state.gov/washington-fellows/',
    quickinfo: {
      Type: 'Fellowship',
      Duration: '6 weeks',
      Location: 'Various U.S. Cities',
      Level: 'Young Professionals',
      Deadline: 'May 15, 2025',
      Funding: 'Fully Funded',
    },
  },
  {
    id: '4',
    icon: '💰',
    title: 'Tony Elumelu Foundation Grant 2025',
    org: 'Tony Elumelu Foundation',
    cat: 'grant',
    loc: 'Pan-African',
    fund: 'Equity / Funding',
    deadline: 'Mar 31, 2025',
    days: 16,
    desc: '$5,000 non-refundable seed capital plus 12-week business training for African entrepreneurs across all 54 African countries.',
    featured: true,
    about: 'The TEF Entrepreneurship Programme is the flagship initiative of the Tony Elumelu Foundation — a $100M commitment to identify, train, mentor, and fund 10,000 African entrepreneurs over 10 years. The 12-week training and mentorship programme empowers African entrepreneurs to launch and scale businesses.',
    elig: [
      'African citizenship or residency in any of 54 African countries',
      'Business idea or early-stage startup (under 3 years old)',
      'Ages 18 and above',
      'Committed to full participation in the 12-week programme',
      'Not previously a TEF Entrepreneur',
    ],
    benefits: [
      '$5,000 non-refundable seed capital',
      '12-week business training curriculum',
      'Mentorship by experienced business leaders',
      'Access to the TEF alumni network (15,000+ entrepreneurs)',
      'Potential for additional investment and support',
    ],
    applyUrl: 'https://tefconnect.com',
    quickinfo: {
      Type: 'Grant + Training',
      Duration: '12-week programme',
      Location: 'Pan-African (Online)',
      Level: 'Early-stage Founders',
      Deadline: 'Mar 31, 2025',
      Amount: '$5,000 seed capital',
    },
  },
  {
    id: '5',
    icon: '🔬',
    title: 'Google STEP Internship 2025',
    org: 'Google · Mountain View',
    cat: 'internship',
    loc: 'United States',
    fund: 'Paid Position',
    deadline: 'Feb 28, 2025',
    days: 2,
    desc: '12-week paid software engineering internship at Google for first and second-year undergraduates from underrepresented groups in tech.',
    featured: false,
    about: 'The Student Training in Engineering Program (STEP) is a 12-week internship for first and second-year undergraduate students with a passion for computer science. It is designed to provide early career experience to students who are members of underrepresented groups.',
    elig: [
      '1st or 2nd year undergraduate student',
      'Studying Computer Science or related engineering field',
      'Experience in at least one programming language',
      'Strong problem-solving and analytical skills',
      'Authorized to work in the US (or apply to international sites)',
    ],
    benefits: [
      'Competitive salary (~$6,000–$8,000/month)',
      'Furnished housing provided or housing stipend',
      'Free meals on Google campus',
      'Relocation assistance if required',
      'Return offer consideration for following years',
    ],
    applyUrl: 'https://careers.google.com/jobs/results/?category=INTERNSHIP',
    quickinfo: {
      Type: 'Internship',
      Duration: '12 weeks (Summer)',
      Location: 'Mountain View, CA',
      Level: 'Undergraduate (Year 1–2)',
      Deadline: 'Feb 28, 2025',
      Stipend: '~$6,000–$8,000/mo',
    },
  },
  {
    id: '6',
    icon: '🚀',
    title: 'Y Combinator W25 (Africa Track)',
    org: 'Y Combinator',
    cat: 'startup',
    loc: 'San Francisco + Remote',
    fund: 'Equity / Funding',
    deadline: 'Oct 10, 2025',
    days: 208,
    desc: 'Apply to the world\'s top startup accelerator. YC invests $500K for 7% equity. African startups are actively encouraged to apply.',
    featured: false,
    about: 'Y Combinator is the world\'s leading startup accelerator, having funded companies like Airbnb, Stripe, Dropbox, and Flutterwave. They invest $500K in early-stage companies in exchange for 7% equity and provide unparalleled mentorship, networking, and resources.',
    elig: [
      'Early-stage startup or compelling idea in any domain',
      '2–4 co-founders preferred (solo founders considered)',
      'Willingness to commit full-time to the startup',
      'Any country of origin — African founders actively encouraged',
      'Willingness to relocate to San Francisco for 3 months',
    ],
    benefits: [
      '$500,000 investment for 7% equity',
      'Access to YC alumni network (10,000+ founders)',
      'Weekly office hours with experienced partners',
      'Demo Day exposure to top-tier investors',
      'Lifetime access to YC resources and deals',
    ],
    applyUrl: 'https://www.ycombinator.com/apply',
    quickinfo: {
      Type: 'Startup Accelerator',
      Duration: '3 months',
      Location: 'San Francisco + Remote',
      Level: 'Pre-seed / Idea Stage',
      Deadline: 'Oct 10, 2025',
      Investment: '$500K for 7% equity',
    },
  },
  {
    id: '7',
    icon: '🎓',
    title: 'DAAD Scholarships for Africa 2025',
    org: 'German Academic Exchange Service',
    cat: 'scholarship',
    loc: 'Germany',
    fund: 'Fully Funded',
    deadline: 'Jun 30, 2025',
    days: 106,
    desc: 'Full scholarships for African students to pursue graduate studies in Germany. Monthly stipend of €850 plus travel allowance.',
    featured: false,
    about: 'The DAAD In-Region Scholarship Programme supports talented students and researchers in sub-Saharan Africa with scholarships for graduate study at excellent African institutions and German universities.',
    elig: [
      'National of a sub-Saharan African country',
      'Bachelor\'s degree with above-average results',
      'Maximum 6 years since graduation for Master\'s applications',
      'German or English language proficiency',
      'Commitment to contributing to home country development',
    ],
    benefits: [
      'Monthly stipend of €850 (approximately ₦1.5M)',
      'Travel allowance to and from Germany',
      'Health insurance coverage',
      'Research or study allowance',
      'German language course support',
    ],
    applyUrl: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
    quickinfo: {
      Type: 'Scholarship',
      Duration: '1–2 years',
      Location: 'Germany',
      Level: 'Masters / PhD',
      Deadline: 'Jun 30, 2025',
      Stipend: '€850/month',
    },
  },
  {
    id: '8',
    icon: '🌍',
    title: 'African Leadership Academy Fellowship',
    org: 'African Leadership Academy',
    cat: 'fellowship',
    loc: 'South Africa',
    fund: 'Fully Funded',
    deadline: 'Apr 20, 2025',
    days: 35,
    desc: 'Two-year transformative pre-university program for exceptional young African leaders. Full scholarship covering tuition, housing, and meals.',
    featured: false,
    about: 'The African Leadership Academy is a two-year, pre-university institution in Johannesburg, South Africa. It brings together the brightest young leaders from across Africa to develop the skills and values needed to transform the continent.',
    elig: [
      'Ages 15–19 at time of enrollment',
      'African national or resident',
      'Demonstrated exceptional academic performance',
      'Leadership experience in school or community',
      'Fluency in English',
    ],
    benefits: [
      'Full scholarship — tuition, housing, and meals covered',
      'World-class faculty and curriculum',
      'Pan-African peer network',
      'University preparation and counseling',
      'Access to ALA alumni network (3,000+ young leaders)',
    ],
    applyUrl: 'https://www.africanleadershipacademy.org/admissions/',
    quickinfo: {
      Type: 'Fellowship / Pre-University',
      Duration: '2 years',
      Location: 'Johannesburg, South Africa',
      Level: 'Secondary / Pre-University',
      Deadline: 'Apr 20, 2025',
      Funding: 'Fully Funded',
    },
  },
]

export function getOpportunity(id: string): Opportunity | undefined {
  return opportunities.find((o) => o.id === id)
}

export function getRelated(id: string, cat: string, limit = 3): Opportunity[] {
  return opportunities.filter((o) => o.id !== id && o.cat === cat).slice(0, limit)
}

export function getFeatured(limit = 6): Opportunity[] {
  return opportunities.filter((o) => o.featured).slice(0, limit)
}
